server:
  port: 8100

zuul:
  routes:
    my-wrapper:
      url: http://localhost:4041
    myendpoint:
      url: http://localhost:4042
  host:
    connect-timeout-millis: 2000
    socket-timeout-millis: 5000


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

